print("test №1", [{'Path': 'geekbrains/california_housing_train.csv', 'Type': 'File', 'Size': 1457},
                  {'Path': 'geekbrains/student_performance.txt', 'Type': 'File', 'Size': 21},
                  {'Path': 'geekbrains/covid.json', 'Type': 'File', 'Size': 35228079},
                  {'Path': 'geekbrains/input2.txt', 'Type': 'File', 'Size': 9},
                  {'Path': 'geekbrains/avg_list.txt', 'Type': 'File', 'Size': 21},
                  {'Path': 'geekbrains/age_report.csv', 'Type': 'File', 'Size': 85},
                  {'Path': 'geekbrains/my_ds_projects', 'Type': 'Directory', 'Size': 684},
                  {'Path': 'geekbrains/my_ds_projects/My-code', 'Type': 'Directory', 'Size': 342},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data', 'Type': 'Directory', 'Size': 171},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'Type': 'File', 'Size': 101},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt', 'Type': 'File',
                   'Size': 70}] == [
          {'Path': 'geekbrains/california_housing_train.csv', 'Type': 'File', 'Size': 1457},
          {'Path': 'geekbrains/student_performance.txt', 'Type': 'File', 'Size': 21},
          {'Path': 'geekbrains/covid.json', 'Type': 'File', 'Size': 35228079},
          {'Path': 'geekbrains/input2.txt', 'Type': 'File', 'Size': 9},
          {'Path': 'geekbrains/avg_list.txt', 'Type': 'File', 'Size': 21},
          {'Path': 'geekbrains/age_report.csv', 'Type': 'File', 'Size': 85},
          {'Path': 'geekbrains/my_ds_projects', 'Type': 'Directory', 'Size': 684},
          {'Path': 'geekbrains/my_ds_projects/My-code', 'Type': 'Directory', 'Size': 342},
          {'Path': 'geekbrains/my_ds_projects/My-code/GB_data', 'Type': 'Directory', 'Size': 171},
          {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'Type': 'File', 'Size': 101},
          {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt', 'Type': 'File', 'Size': 70}]
      )

print("test №2", [{'Path': 'geekbrains/my_ds_projects/My-code', 'Type': 'Directory', 'Size': 342},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data', 'Type': 'Directory', 'Size': 171},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'Type': 'File', 'Size': 101},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt', 'Type': 'File',
                   'Size': 70}] == [{'Path': 'geekbrains/my_ds_projects/My-code', 'Type': 'Directory', 'Size': 342},
                                    {'Path': 'geekbrains/my_ds_projects/My-code/GB_data', 'Type': 'Directory',
                                     'Size': 171},
                                    {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'Type': 'File',
                                     'Size': 101},
                                    {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt',
                                     'Type': 'File', 'Size': 70}]

      )

print("test №3", [{'Path': 'geekbrains/california_housing_train.csv', 'Type': 'File', 'Size': 1457},
                  {'Path': 'geekbrains/student_performance.txt', 'Type': 'File', 'Size': 21},
                  {'Path': 'geekbrains/covid.json', 'Type': 'File', 'Size': 35228079},
                  {'Path': 'geekbrains/input2.txt', 'Type': 'File', 'Size': 9},
                  {'Path': 'geekbrains/avg_list.txt', 'Type': 'File', 'Size': 21},
                  {'Path': 'geekbrains/age_report.csv', 'Type': 'File', 'Size': 85},
                  {'Path': 'geekbrains/my_ds_projects', 'Type': 'Directory', 'Size': 684},
                  {'Path': 'geekbrains/my_ds_projects/My-code', 'Type': 'Directory', 'Size': 342},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data', 'Type': 'Directory', 'Size': 171},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'Type': 'File', 'Size': 101},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt', 'Type': 'File',
                   'Size': 70}] == [{'Path': 'geekbrains/california_housing_train.csv', 'Type': 'File', 'Size': 1457},
                                    {'Path': 'geekbrains/student_performance.txt', 'Type': 'File', 'Size': 21},
                                    {'Path': 'geekbrains/covid.json', 'Type': 'File', 'Size': 35228079},
                                    {'Path': 'geekbrains/input2.txt', 'Type': 'File', 'Size': 9},
                                    {'Path': 'geekbrains/avg_list.txt', 'Type': 'File', 'Size': 21},
                                    {'Path': 'geekbrains/age_report.csv', 'Type': 'File', 'Size': 85},
                                    {'Path': 'geekbrains/my_ds_projects', 'Type': 'Directory', 'Size': 684},
                                    {'Path': 'geekbrains/my_ds_projects/My-code', 'Type': 'Directory', 'Size': 342},
                                    {'Path': 'geekbrains/my_ds_projects/My-code/GB_data', 'Type': 'Directory',
                                     'Size': 171},
                                    {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'Type': 'File',
                                     'Size': 101},
                                    {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt',
                                     'Type': 'File', 'Size': 70}]

      )
print("test №4", [['Path', 'Type', 'Size'], ['geekbrains/california_housing_train.csv', 'File', '1457'],
                  ['geekbrains/student_performance.txt', 'File', '21'], ['geekbrains/covid.json', 'File', '35228079'],
                  ['geekbrains/input2.txt', 'File', '9'], ['geekbrains/avg_list.txt', 'File', '21'],
                  ['geekbrains/age_report.csv', 'File', '85'], ['geekbrains/my_ds_projects', 'Directory', '684'],
                  ['geekbrains/my_ds_projects/My-code', 'Directory', '342'],
                  ['geekbrains/my_ds_projects/My-code/GB_data', 'Directory', '171'],
                  ['geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'File', '101'],
                  ['geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt', 'File', '70']] == [
          ['Path', 'Type', 'Size'], ['geekbrains/california_housing_train.csv', 'File', '1457'],
          ['geekbrains/student_performance.txt', 'File', '21'], ['geekbrains/covid.json', 'File', '35228079'],
          ['geekbrains/input2.txt', 'File', '9'], ['geekbrains/avg_list.txt', 'File', '21'],
          ['geekbrains/age_report.csv', 'File', '85'], ['geekbrains/my_ds_projects', 'Directory', '684'],
          ['geekbrains/my_ds_projects/My-code', 'Directory', '342'],
          ['geekbrains/my_ds_projects/My-code/GB_data', 'Directory', '171'],
          ['geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'File', '101'],
          ['geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt', 'File', '70']]
      )

print("test №5", [{'Path': 'geekbrains/california_housing_train.csv', 'Type': 'File', 'Size': 1457},
                  {'Path': 'geekbrains/student_performance.txt', 'Type': 'File', 'Size': 21},
                  {'Path': 'geekbrains/covid.json', 'Type': 'File', 'Size': 35228079},
                  {'Path': 'geekbrains/input2.txt', 'Type': 'File', 'Size': 9},
                  {'Path': 'geekbrains/avg_list.txt', 'Type': 'File', 'Size': 21},
                  {'Path': 'geekbrains/age_report.csv', 'Type': 'File', 'Size': 85},
                  {'Path': 'geekbrains/my_ds_projects', 'Type': 'Directory', 'Size': 684},
                  {'Path': 'geekbrains/my_ds_projects/My-code', 'Type': 'Directory', 'Size': 342},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data', 'Type': 'Directory', 'Size': 171},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'Type': 'File', 'Size': 101},
                  {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt', 'Type': 'File',
                   'Size': 70}] == [{'Path': 'geekbrains/california_housing_train.csv', 'Type': 'File', 'Size': 1457},
                                    {'Path': 'geekbrains/student_performance.txt', 'Type': 'File', 'Size': 21},
                                    {'Path': 'geekbrains/covid.json', 'Type': 'File', 'Size': 35228079},
                                    {'Path': 'geekbrains/input2.txt', 'Type': 'File', 'Size': 9},
                                    {'Path': 'geekbrains/avg_list.txt', 'Type': 'File', 'Size': 21},
                                    {'Path': 'geekbrains/age_report.csv', 'Type': 'File', 'Size': 85},
                                    {'Path': 'geekbrains/my_ds_projects', 'Type': 'Directory', 'Size': 684},
                                    {'Path': 'geekbrains/my_ds_projects/My-code', 'Type': 'Directory', 'Size': 342},
                                    {'Path': 'geekbrains/my_ds_projects/My-code/GB_data', 'Type': 'Directory',
                                     'Size': 171},
                                    {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/fruits.csv', 'Type': 'File',
                                     'Size': 101},
                                    {'Path': 'geekbrains/my_ds_projects/My-code/GB_data/list_of_names.txt',
                                     'Type': 'File', 'Size': 70}]

      )
